encoding: utf-8
site.url: skishop-lelex.com
skimium-url: http://www.skimium.fr/store/ski-shop-lelex-167
fb-page-url: https://www.facebook.com/skishop.lelex
google-url: https://plus.google.com/+Skishop-lelex
twitter-url: https://twitter.com/skishoplelex
analytics-key: UA-11574769-1
